name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: "Run Specific Job"
        type: boolean
        required: false
        default: true
      custom_message:
        description: "Enter a custom message"
        type: string
        required: true

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: |
          echo "Printing Custom Message : ${{ github.event.inputs.custom_message }}"